stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/discordbots:v1
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
